config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "projects#index"

  scope "/:user_id", as: :user do
    resources :projects, only: %i[index new edit update create destroy], param: :slug do
      resources :events, only: %i[index show], param: :slug
      resources :funnels, param: :slug
      get "settings", to: "projects#settings"
    end
  end

  scope module: "users" do
    get "settings/", to: "settings#show", as: :users_settings
  end

  scope "stripe/" do
    get "/checkout_session/", to: "stripe#checkout_session", as: "stripe_checkout_session"
    get "/success_callback/", to: "stripe#success_callback", as: "stripe_success_callback"
    get "/customer_portal/", to: "stripe#customer_portal", as: "stripe_customer_portal"
    post "/webhooks/", to: "stripe#webhooks", as: "stripe_webhooks"
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }

  namespace :api do
    namespace :v1 do
      resources :events, only: %i[create]
    end
  end

  if Rails.env.development?
    namespace :development do
      resources :embed_mock, only: [:index]
    end
  end
end

app/views/partials/_footer.html.erb
<footer class="bg-green-100 mt-auto text-gray-600">
  <div class="flex flex-col md:flex-row items-center justify-between p-6 w-full gap-y-4 md:gap-y-0">
    <div class="text-center md:text-left">
      Fugu is 100% self-funded, independent and hosted in the EU.
      By <a href="https://twitter.com/canolcer" target="_blank">@canolcer</a>.
    </div>
    <div class="flex flex-wrap max-w-full items-center justify-center gap-x-4">
      <a href="https://fugu.lol" target="_blank" class="no-underline font-normal">About</a>
      <a href="https://docs.fugu.lol" target="_blank" class="no-underline font-normal">Docs</a>
      <a href="https://github.com/shafy/fugu" target="_blank" class="no-underline font-normal">GitHub</a>
      <a href="https://fugu.lol/legal/terms" class="no-underline font-normal" target="_blank">Terms</a>
      <a href="https://fugu.lol/legal/privacy" class="no-underline font-normal" target="_blank">Privacy</a>
      <a href="https://fugu.lol/legal/dpa" class="no-underline font-normal" target="_blank">DPA</a>
      <a href="https://fugu.lol/legal/imprint" class="no-underline font-normal" target="_blank">Imprint</a>
    </div>
  </div>
</footer>

app/views/partials/_header.html.erb
<header class="bg-green-100 shadow-sm">
  <div class="flex flex-row items-center justify-between p-4 w-full">
    <div class="w-10">
      <a href="/" class="no-underline"><%= image_tag "fugu_logo.png" %></a>
    </div>
    <div>
      <% if current_user %>
        <a href="https://docs.fugu.lol" target="_blank" class="no-underline mx-2">Docs</a>
        <a href="<%= user_projects_path(current_user.hash_id) %>" class="no-underline mx-2">Projects</a>
        <a href="<%= users_settings_path %>" class="no-underline mx-2">Account settings</a>
      <% end %>
    </div>
  </div>
</header>

app/views/partials/_mode_toggle.html.erb
<% if test_mode %>
  <%= link_to "Toggle LIVE mode", build_test_toggle_url(params, aggregation, false, chart_type), class: "font-normal" %>
<% else %>
  <%= link_to "Toggle TEST mode", build_test_toggle_url(params, aggregation, true, chart_type), class: "font-normal" %>
<% end %>

app/views/partials/_narrow_box.erb
<div class="flex flex-col w-full md:w-32rem mb-4 p-4 rounded-md shadow-md bg-yellow-50 gap-x-5">
  <%= yield %>
</div>

app/views/partials/_project_header.html.erb
<div class="flex flex-row items-center justify-between w-full mb-2">
  <div class="flex flex-row items-center justify-start w-full text-left">
    <div class="text-lg font-medium mr-6"><%= project_name %></div>
    
  </div>
  <%= link_to "Events",
    user_project_events_path(params[:user_id], @project.name, evergreen_params)
  %>
  <%= link_to "Funnels",
    user_project_funnels_path(params[:user_id], @project.name, evergreen_params),
    class: "ml-4"
  %>
</div>