config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "projects#index"

  scope "/:user_id", as: :user do
    resources :projects, only: %i[index new edit update create destroy], param: :slug do
      resources :events, only: %i[index show], param: :slug
      resources :funnels, param: :slug
      get "settings", to: "projects#settings"
    end
  end

  scope module: "users" do
    get "settings/", to: "settings#show", as: :users_settings
  end

  scope "stripe/" do
    get "/checkout_session/", to: "stripe#checkout_session", as: "stripe_checkout_session"
    get "/success_callback/", to: "stripe#success_callback", as: "stripe_success_callback"
    get "/customer_portal/", to: "stripe#customer_portal", as: "stripe_customer_portal"
    post "/webhooks/", to: "stripe#webhooks", as: "stripe_webhooks"
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }

  namespace :api do
    namespace :v1 do
      resources :events, only: %i[create]
    end
  end

  if Rails.env.development?
    namespace :development do
      resources :embed_mock, only: [:index]
    end
  end
end

app/models/project.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: projects
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  public     :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_projects_on_name_and_user_id  (name,user_id) UNIQUE
#  index_projects_on_user_id           (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Project < ApplicationRecord
  has_many :api_keys, dependent: :destroy
  belongs_to :user

  validates :name,
            presence: true,
            length: { maximum: 40 },
            uniqueness: {
              scope: :user_id,
              message: "You already have a project with this name",
              case_insensitive: true
            },
            format:
              {
                with: /\A[a-zA-Z0-9-]*\z/,
                message: "can only contain numbers, letters and hyphens"
              },
            exclusion:
              {
                in: %w[project projects],
                message: "'%{value}' is a reversed event name by Fugu and can't be used"
              }

  before_validation :downcase_name
  before_validation :strip_name

  def downcase_name
    self.name = name.downcase if name
  end

  def strip_name
    self.name = name.strip if name
  end

  def create_api_keys
    ApiKey.create(project: self, test: false)
    ApiKey.create(project: self, test: true)
  end

  def api_key_live
    api_keys.find_by(test: false)
  end

  def api_key_test
    api_keys.find_by(test: true)
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_project, only: %i[settings]
  before_action :show_not_active_flash, only: %i[settings]

  def index
    @projects = Project.where(user: current_user)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(name: project_params[:name], user: current_user)
    if @project.save
      @project.create_api_keys
      redirect_to user_project_events_path(current_user.hash_id, @project.name)
    else
      flash.now[:error] = "We couldn't create your project: #{@project.errors.full_messages.first}"
      render "projects/new", status: :unprocessable_entity
    end
  end

  def edit
    user = User.find_by(hash_id: params[:user_id])
    @project = Project.find_by(name: params[:slug]&.downcase, user: user)
  end

  def update
    @project = Project.find(project_params[:project_id])

    if @project.update(name: project_params[:name], public: project_params[:public])
      redirect_to user_project_settings_path(current_user.hash_id, @project.name.downcase)
    else
      flash.now[:error] = "We couldn't update your project: #{@project.errors.full_messages.first}"
      render "projects/edit", status: :unprocessable_entity
    end
  end

  def destroy
    @project = Project.find_by(name: params[:slug]&.downcase, user: current_user)
    if @project.destroy
      flash[:notice] = "Your project was successfully deleted"
      redirect_to user_projects_path(current_user)
    else
      flash[:error] = "We couldn't delete the project: #{@project.errors.full_messages.first}"
      redirect_to user_project_events_path(current_user.hash_id, @project.name)
    end
  end

  def settings; end

  private

  def project_params
    params.require(:project).permit(:project_id, :user_id, :name, :public)
  end
end

app/views/projects/edit.html.erb
<% content_for :main do %>
  <h1>Edit project</h1>
  <%= form_with model: @project, url: user_project_path do |form| %>
    <div class="mb-4 w-80">
      <div class="mb-2">
        <%= form.label :name, 'Project name' %>
      </div>
      <%= form.text_field :name, autofocus: true, required: true, class: "rounded-lg w-full" %>
      <em class="text-sm text-gray-600">
        Project name can't include any special characters except "-".
      </em>
    </div>
    <div class="mb-4 w-80">
      <div class="mb-2">
        <%= form.label :public, 'Make public' %>
        <%= form.check_box :public, class: 'ml-2' %>
      </div>
      <em class="text-sm text-gray-600">
        Public projects can be viewed by anyone who has this URL.
      </em>
    </div>
    <%= form.hidden_field :project_id, value: @project.id %>
    <div cass="mb-4">
      <%= form.submit 'Update', class: 'main-button' %>
    </div>
  <% end %>
<% end %>

app/views/projects/index.html.erb
<% content_for :main do %>
<h1 class="text-xl font-medium mb-8">Projects</h1>
  <%= render "partials/narrow_box" do %>
    <% if @projects.any? %>
      <% @projects.each do |project| %>
        <div class="mb-2">
          <%= link_to project.name, user_project_events_path(current_user.hash_id, project.name), class: "no-underline text-lg" %>
        </div>
      <% end %>
    <% else %>
      <p class="mb-2">
        Welcome to Fugu 👋 To get started, add a new project
        and track your first event by calling the Fugu API.
        Have a look at the
        <a href="https://docs.fugu.lol" target="_blank">docs</a> for more info.
      </p>
    <% end %>
    <%= link_to 'Add a new project', new_user_project_path(current_user.hash_id), class: "mt-4" %>
  <% end %>
<% end %>

app/views/projects/new.html.erb
<% content_for :main do %>
  <h1>Add a new project</h1>
  <%= form_with model: @project, url: user_projects_path do |form| %>
    <div class="mb-4 w-80">
      <div class="mb-2">
        <%= form.label :name, 'Project name' %>
      </div>
      <%= form.text_field :name, autofocus: true, required: true, class: 'rounded-lg w-full' %>
      <em class="text-sm text-gray-600">
        Project name can't include any special characters except "-".
      </em>
    </div>
    <div cass="mb-4">
      <%= form.submit 'Add', class: 'main-button' %>
    </div>
  <% end %>
<% end %>

app/views/projects/settings.html.erb
<% content_for :main do %>
  <h1 class="text-xl font-medium mb-8">Project settings</h1>
  <%= render "partials/narrow_box" do %>
    <h2>Project name</h2>
    <p>
      <%= @project.name %>
    </p>
    <h2>Visibility</h2>
    <p>
      <% unless @project.public %>
        This project is private.
      <% else %>
        This project is public. Share the project URL with your friends to impress them.
      <% end %>
    </p>
    <h2>API keys</h2>
    <div>
      <div class="font-medium mb-2">Test API key</div> <code><%= @project.api_key_test.key_value %></code>
      <div class="text-sm text-gray-600 mb-2 mt-2">Test events are deleted after 14 days</div>
      <div class="font-medium mb-2 mt-4">Live API key</div> <code><%=  @project.api_key_live.key_value %></code>
    </div>
    <h2 class="mt-6">Embedding</h2>
    <% if @project.public %>
      <p>
        Copy and paste the embed code anywhere to display your project.
        Your project's visibility needs to be set to public.
        Check out the <a href="https://docs.fugu.lol/projects/embedding-a-project" target="_blank">docs</a>
        to learn how to customize your embed code.
      </p>
      <div class="code--multiline">
        <code>
          <%=
            %(<iframe src="#{user_project_events_url(current_user.hash_id, @project.name, { embed: true })}" title="Fugu" loading="lazy" referrerpolicy="no-referrer" height="800px" width="900px"></iframe>)
          %>
        </code>
      </div>
    <% else %>
      To display your embed code, edit your project and set it's visibility to public.
    <% end %>
    <div class="mt-6 mb-4">
      <%= link_to "Edit project",
          edit_user_project_path(current_user.hash_id, @project.name),
          class: "bg-transparent underline font-medium hover:text-green-500 cursor-pointer"
      %>
      <%= button_to "Delete project",
          user_project_path(current_user.hash_id, @project.name),
          method: :delete,
          class: "bg-transparent underline font-medium hover:text-green-500 cursor-pointer mt-2",
          onclick: "return confirm('This will delete this project and all its events forever. Are you sure?');"
      %>
    </div>
  <% end %>
  <%= link_to "Back to #{@project.name}", user_project_events_path(current_user.hash_id, @project.name) %>
<% end %>