config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "projects#index"

  scope "/:user_id", as: :user do
    resources :projects, only: %i[index new edit update create destroy], param: :slug do
      resources :events, only: %i[index show], param: :slug
      resources :funnels, param: :slug
      get "settings", to: "projects#settings"
    end
  end

  scope module: "users" do
    get "settings/", to: "settings#show", as: :users_settings
  end

  scope "stripe/" do
    get "/checkout_session/", to: "stripe#checkout_session", as: "stripe_checkout_session"
    get "/success_callback/", to: "stripe#success_callback", as: "stripe_success_callback"
    get "/customer_portal/", to: "stripe#customer_portal", as: "stripe_customer_portal"
    post "/webhooks/", to: "stripe#webhooks", as: "stripe_webhooks"
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }

  namespace :api do
    namespace :v1 do
      resources :events, only: %i[create]
    end
  end

  if Rails.env.development?
    namespace :development do
      resources :embed_mock, only: [:index]
    end
  end
end

app/models/funnel.rb
# == Schema Information
#
# Table name: funnels
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  api_key_id :bigint           not null
#
# Indexes
#
#  index_funnels_on_api_key_id           (api_key_id)
#  index_funnels_on_name_and_api_key_id  (name,api_key_id) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (api_key_id => api_keys.id)
#

# frozen_string_literal: true

class Funnel < ApplicationRecord
  belongs_to :api_key

  has_many :funnel_steps, dependent: :destroy
  accepts_nested_attributes_for :funnel_steps,
                                reject_if: ->(attr) { attr[:event_name].blank? }

  validates :name,
            presence: true,
            uniqueness: {
              scope: :api_key_id,
              message: "You already have a funnel with this name",
              case_insensitive: true
            },
            format:
              {
                with: /\A[a-zA-Z0-9\s]*\z/,
                message: "can only contain numbers, letters and spaces"
              }

  validates :funnel_steps, presence: { message: "- Add at least one funnel step" }

  before_validation :titleize_name
  before_validation :strip_name

  FUNNEL_PARAMS = %i[user_id project_slug slug test event prop date embed].freeze

  private

  def titleize_name
    self.name = name.downcase.titleize if name
  end

  def strip_name
    self.name = name.strip if name
  end
end

app/controllers/funnels_controller.rb
# frozen_string_literal: true

class FunnelsController < ApplicationController
  include ApiKeyable
  include Dateable
  include EventNameable

  before_action :set_project, only: %i[show index new create]
  before_action :authenticate_user!, unless: -> { @project.public }
  before_action :authorize_project_user, only: %i[index new]
  before_action :show_test_alert, only: %i[show index]
  before_action :show_test_funnel_creation_alert, only: %i[new]
  before_action :show_not_active_flash, only: %i[index]
  before_action :set_api_key, only: %i[index show new create]
  before_action :set_dates, only: %i[show]
  before_action :set_event_names, only: %i[new]
  before_action :set_funnel, only: %i[show]
  before_action :set_funnel_names, only: %i[index show]
  before_action :set_funnel_event_names, only: %i[show]
  before_action :build_funnel, only: %i[create]

  after_action :track_event, only: %i[index]
  after_action :allow_iframe, only: %i[index show]

  def index
    return render layout: "data_view" unless @funnel_names&.first

    redirect_to user_project_funnel_path(
      params[:user_id],
      @project.name,
      @funnel_names.first.parameterize,
      helpers.evergreen_params
    )
  end

  def show
    unless @funnel
      return redirect_to user_project_funnels_path(
        params[:user_id],
        @project.name,
        helpers.evergreen_params
      )
    end

    @funnel_data = @funnel_event_names.map do |e|
      Event.where(name: e, api_key: @api_key, created_at: @start_date..@end_date).count
    end
    render layout: "data_view"
  end

  def new
    @funnel = Funnel.new
    5.times { @funnel.funnel_steps.build }

    show_no_events_alert if @event_names.empty?
  end

  def create
    if @funnel.save
      redirect_to user_project_funnel_path(
        current_user.hash_id,
        @project.name,
        @funnel.name.parameterize,
        params: { test: params[:test] }
      )
    else
      flash[:error] = "We couldn't create your funnel: #{@funnel.errors.full_messages.first}"
      redirect_to new_user_project_funnel_path(
        current_user.hash_id,
        @project.name,
        params: { test: params[:test] }
      )
    end
  end

  private

  def funnel_params
    params.require(:funnel).permit(:user_id, :name, funnel_steps_attributes: %w[event_name])
  end

  def track_event
    FuguService.track("Viewed Funnels")
  end

  def build_funnel
    @funnel = Funnel.new(funnel_params.merge(api_key: @api_key))
  end

  def set_funnel
    @funnel = Funnel.find_by(name: params[:slug].tr("-", " ").titleize.strip, api_key: @api_key)
  end

  def set_funnel_names
    @funnel_names = Funnel.where(api_key: @api_key).pluck(:name)
  end

  def set_funnel_event_names
    @funnel_event_names = @funnel&.funnel_steps&.pluck(:event_name)
  end

  def show_test_funnel_creation_alert
    return unless params[:test] == "true"

    flash.now[:info] = "You are creating a funnel in test mode. " \
                       "This means that you can only select events tracked in test mode. " \
                       "Unlike test events, test funnels are not deleted after 14 days."
  end

  def show_no_events_alert
    flash.now[:alert] = "You haven't tracked any events in the current mode. " \
                        "Make sure to track events before creating a funnel."
  end
end

app/views/funnels/_chart.html.erb
<div class="flex flex-col w-full p-4 rounded-md shadow-md bg-yellow-50">
  <div data-controller="funnel-chart"
        data-funnel-chart-funnel-event-names-value="<%= funnel_event_names.to_json %>"
        data-funnel-chart-funnel-data-value="<%= funnel_data.to_json %>"
        class="h-[28rem]"
  >
    <canvas data-funnel-chart-target="chart" class="h-full pt-4"></canvas>
  </div>
</div>

app/views/funnels/_selections.html.erb
<div
  class="flex flex-col md:flex-row w-full items-left md:items-center justify-between"
  data-controller="selection"
>
  <div class="flex flex-col md:flex-row gap-x-5 items-left md:items-center justify-start">
    <div class="flex flex-col items-start justify-center mb-2 md:mb-0">
      <%= label_tag 'funnels', 'Funnels', class: "text-sm font-medium mb-2" %>
      <%= select_tag "funnels",
          raw(funnel_select_options(param_data, funnel_names)),
          data: { action: "change->selection#navigateToSelectUrl" },
          class: "w-56 text-sm"
      %>
    </div>
  </div>
  <div class="flex flex-col md:flex-row gap-x-5 items-left md:items-center justify-start">
    <div class="flex flex-col items-start justify-center mb-2 md:mb-0">
      <%= label_tag 'date_range', 'Date Range', class: "text-sm font-medium mb-2" %>
      <%= select_tag "date_range",
          raw(date_select_options(param_data, nil, "funnel")),
          data: { action: "change->selection#navigateToSelectUrl" },
          class: "text-sm"
      %>
    </div>
  </div>
</div>

app/views/funnels/index.html.erb
<% content_for :project_header do %>
  <%= render partial: "partials/project_header", locals: { project_name: @project.name } %>
<% end %>

<% content_for :no_data do %>
  <p>
    You haven't created any funnels for this project yet.
    <% if current_user %>
        <%# we don't want to show the rest for public projects %>
      To get started, <%= link_to "create a funnel", new_user_project_funnel_path(current_user.hash_id, @project.name, params: { test: params[:test] }) %>.<br><br>
      <% if params[:test] == "true" %>
        Did you create funnels in live mode?
        <%= link_to "Toggle live mode!", user_project_funnels_path(current_user.hash_id, @project.name) %>
      <% else %>
        Did you create funnels in test mode?
        <%= link_to "Toggle test mode!", user_project_funnels_path(current_user.hash_id, @project.name, params: { test: true }) %>
      <% end %>
    <% end %>
  </p>
<% end %>

app/views/funnels/new.html.erb
<% content_for :main do %>
  <h1 class="text-xl font-medium mb-8">Create new funnel</h1>
  <%= render "partials/narrow_box" do %>
    <%= form_with model: @funnel, url: user_project_funnels_path do |funnel_form| %>
      <p>Give your funnel a name:</p>
      <div class="flex flex-row items-center justify-start w-full mt-6 mb-8">
        <div class="w-20">
          <%= funnel_form.label :name, "Name" %>
        </div>
        <%= funnel_form.text_field :name, required: true, placeholder: "E.g., Sign up to subscription", class: "w-64 rounded border-2 border-gray-600" %>
      </div>
      <p>Select an event for each funnel step:</p>
      <div class="flex flex-col items-center justify-start w-full gap-y-4 my-6">
        <%= funnel_form.fields_for :funnel_steps do |funnel_steps_form| %>
          <div class="flex flex-row items-center justify-start w-full">
            <div class="w-20">
              <%= funnel_steps_form.label :event_name, "Step #{funnel_steps_form.index + 1}" %>
            </div>
            <%= 
              funnel_steps_form.select :event_name,
              options_for_select(@event_names, "Select event"),
              {include_blank: "Select event"},
              required: false, #funnel_steps_form.index == 0,
              class: "w-64"
            %>
          </div>
        <% end %>
      </div>
      <%= hidden_field_tag "test", params[:test] %>
      <%= funnel_form.submit "Create funnel", class: "main-button" %>
    <% end %>
  <% end %>
  <%= link_to "Cancel and go back to #{@project.name}", user_project_events_path(current_user.hash_id, @project.name) %>
  <% if params[:test] == "true" %>
    <%= link_to "Toggle LIVE mode", new_user_project_funnel_path(current_user.hash_id, @project.name, params: { test: false }), class: "font-normal mt-2" %>
  <% else %>
    <%= link_to "Toggle TEST mode", new_user_project_funnel_path(current_user.hash_id, @project.name, params: { test: true }), class: "font-normal mt-2" %>
  <% end %>
<% end %>

app/views/funnels/show.html.erb
<% content_for :project_header do %>
  <%= render partial: "partials/project_header", locals: { project_name: @project.name } %>
<% end %>

<% content_for :data_controls do %>
  <%= render partial: "selections",
          locals: {
            param_data: params,
            funnel_names: @funnel_names,
            properties: @properties
          }
      %>
<% end%>

<% content_for :chart_view do %>
  <%= render partial: "chart",
    locals: {
      funnel_event_names: @funnel_event_names,
      funnel_data: @funnel_data,
    }
  %>
<% end %>

<% content_for :project_footer do %>
  <div class="flex flex-row items-center justify-end w-full my-4 gap-x-4">
    <%= link_to "Create new funnel",
        new_user_project_funnel_path(params[:user_id], @project.name, params: { test: params[:test] }),
        class: "font-normal"
    %>
    <%= link_to "Project settings", user_project_settings_path(params[:user_id]), class: "font-normal" %>
    <%= render partial: "partials/mode_toggle",
      locals: {
        project_name: @project.name,
        test_mode: params[:test] == "true",
        aggregation: nil,
        chart_type: "funnel"
      } if current_user
    %>
  </div>
<% end %>